// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ApplicationType int32

const (
	ApplicationType_SERVER  ApplicationType = 0
	ApplicationType_CRONJOB ApplicationType = 1
)

var ApplicationType_name = map[int32]string{
	0: "SERVER",
	1: "CRONJOB",
}
var ApplicationType_value = map[string]int32{
	"SERVER":  0,
	"CRONJOB": 1,
}

func (x ApplicationType) String() string {
	return proto1.EnumName(ApplicationType_name, int32(x))
}
func (ApplicationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

type CreationState int32

const (
	CreationState_CREATE_INFRASTRUCTURE_WAIT      CreationState = 0
	CreationState_CREATE_INFRASTRUCTURE_SUCCEEDED CreationState = 1
	CreationState_CREATE_INFRASTRUCTURE_FAILED    CreationState = 2
)

var CreationState_name = map[int32]string{
	0: "CREATE_INFRASTRUCTURE_WAIT",
	1: "CREATE_INFRASTRUCTURE_SUCCEEDED",
	2: "CREATE_INFRASTRUCTURE_FAILED",
}
var CreationState_value = map[string]int32{
	"CREATE_INFRASTRUCTURE_WAIT":      0,
	"CREATE_INFRASTRUCTURE_SUCCEEDED": 1,
	"CREATE_INFRASTRUCTURE_FAILED":    2,
}

func (x CreationState) String() string {
	return proto1.EnumName(CreationState_name, int32(x))
}
func (CreationState) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

type DeletionState int32

const (
	DeletionState_NOT_DELETED                     DeletionState = 0
	DeletionState_DELETE_INFRASTRUCTURE_WAIT      DeletionState = 1
	DeletionState_DELETE_INFRASTRUCTURE_SUCCEEDED DeletionState = 2
	DeletionState_DELETE_INFRASTRUCTURE_FAILED    DeletionState = 3
)

var DeletionState_name = map[int32]string{
	0: "NOT_DELETED",
	1: "DELETE_INFRASTRUCTURE_WAIT",
	2: "DELETE_INFRASTRUCTURE_SUCCEEDED",
	3: "DELETE_INFRASTRUCTURE_FAILED",
}
var DeletionState_value = map[string]int32{
	"NOT_DELETED":                     0,
	"DELETE_INFRASTRUCTURE_WAIT":      1,
	"DELETE_INFRASTRUCTURE_SUCCEEDED": 2,
	"DELETE_INFRASTRUCTURE_FAILED":    3,
}

func (x DeletionState) String() string {
	return proto1.EnumName(DeletionState_name, int32(x))
}
func (DeletionState) EnumDescriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

type Application struct {
	Id                 int32                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId             int32                      `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Name               string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description        string                     `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	ExternalDns        string                     `protobuf:"bytes,5,opt,name=external_dns,json=externalDns" json:"external_dns,omitempty"`
	GithubRepoUrl      string                     `protobuf:"bytes,6,opt,name=github_repo_url,json=githubRepoUrl" json:"github_repo_url,omitempty"`
	DockerfilePath     string                     `protobuf:"bytes,7,opt,name=dockerfile_path,json=dockerfilePath" json:"dockerfile_path,omitempty"`
	EntrypointOverride string                     `protobuf:"bytes,8,opt,name=entrypoint_override,json=entrypointOverride" json:"entrypoint_override,omitempty"`
	Type               ApplicationType            `protobuf:"varint,9,opt,name=type,enum=soapbox.ApplicationType" json:"type,omitempty"`
	CreatedAt          *google_protobuf.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	Slug               string                     `protobuf:"bytes,11,opt,name=slug" json:"slug,omitempty"`
	InternalDns        string                     `protobuf:"bytes,12,opt,name=internal_dns,json=internalDns" json:"internal_dns,omitempty"`
	CreationState      CreationState              `protobuf:"varint,13,opt,name=creation_state,json=creationState,enum=soapbox.CreationState" json:"creation_state,omitempty"`
	DeletionState      DeletionState              `protobuf:"varint,14,opt,name=deletion_state,json=deletionState,enum=soapbox.DeletionState" json:"deletion_state,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto1.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Application) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Application) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetExternalDns() string {
	if m != nil {
		return m.ExternalDns
	}
	return ""
}

func (m *Application) GetGithubRepoUrl() string {
	if m != nil {
		return m.GithubRepoUrl
	}
	return ""
}

func (m *Application) GetDockerfilePath() string {
	if m != nil {
		return m.DockerfilePath
	}
	return ""
}

func (m *Application) GetEntrypointOverride() string {
	if m != nil {
		return m.EntrypointOverride
	}
	return ""
}

func (m *Application) GetType() ApplicationType {
	if m != nil {
		return m.Type
	}
	return ApplicationType_SERVER
}

func (m *Application) GetCreatedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Application) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Application) GetInternalDns() string {
	if m != nil {
		return m.InternalDns
	}
	return ""
}

func (m *Application) GetCreationState() CreationState {
	if m != nil {
		return m.CreationState
	}
	return CreationState_CREATE_INFRASTRUCTURE_WAIT
}

func (m *Application) GetDeletionState() DeletionState {
	if m != nil {
		return m.DeletionState
	}
	return DeletionState_NOT_DELETED
}

type ListApplicationRequest struct {
	UserId int32 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *ListApplicationRequest) Reset()                    { *m = ListApplicationRequest{} }
func (m *ListApplicationRequest) String() string            { return proto1.CompactTextString(m) }
func (*ListApplicationRequest) ProtoMessage()               {}
func (*ListApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *ListApplicationRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListApplicationResponse struct {
	Applications []*Application `protobuf:"bytes,1,rep,name=applications" json:"applications,omitempty"`
}

func (m *ListApplicationResponse) Reset()                    { *m = ListApplicationResponse{} }
func (m *ListApplicationResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListApplicationResponse) ProtoMessage()               {}
func (*ListApplicationResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *ListApplicationResponse) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

type GetApplicationRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetApplicationRequest) Reset()                    { *m = GetApplicationRequest{} }
func (m *GetApplicationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetApplicationRequest) ProtoMessage()               {}
func (*GetApplicationRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *GetApplicationRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto1.RegisterType((*Application)(nil), "soapbox.Application")
	proto1.RegisterType((*ListApplicationRequest)(nil), "soapbox.ListApplicationRequest")
	proto1.RegisterType((*ListApplicationResponse)(nil), "soapbox.ListApplicationResponse")
	proto1.RegisterType((*GetApplicationRequest)(nil), "soapbox.GetApplicationRequest")
	proto1.RegisterEnum("soapbox.ApplicationType", ApplicationType_name, ApplicationType_value)
	proto1.RegisterEnum("soapbox.CreationState", CreationState_name, CreationState_value)
	proto1.RegisterEnum("soapbox.DeletionState", DeletionState_name, DeletionState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Applications service

type ApplicationsClient interface {
	ListApplications(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error)
	CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error)
	GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error)
	DeleteApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Empty, error)
}

type applicationsClient struct {
	cc *grpc.ClientConn
}

func NewApplicationsClient(cc *grpc.ClientConn) ApplicationsClient {
	return &applicationsClient{cc}
}

func (c *applicationsClient) ListApplications(ctx context.Context, in *ListApplicationRequest, opts ...grpc.CallOption) (*ListApplicationResponse, error) {
	out := new(ListApplicationResponse)
	err := grpc.Invoke(ctx, "/soapbox.Applications/ListApplications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) CreateApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/CreateApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) GetApplication(ctx context.Context, in *GetApplicationRequest, opts ...grpc.CallOption) (*Application, error) {
	out := new(Application)
	err := grpc.Invoke(ctx, "/soapbox.Applications/GetApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationsClient) DeleteApplication(ctx context.Context, in *Application, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/soapbox.Applications/DeleteApplication", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Applications service

type ApplicationsServer interface {
	ListApplications(context.Context, *ListApplicationRequest) (*ListApplicationResponse, error)
	CreateApplication(context.Context, *Application) (*Application, error)
	GetApplication(context.Context, *GetApplicationRequest) (*Application, error)
	DeleteApplication(context.Context, *Application) (*Empty, error)
}

func RegisterApplicationsServer(s *grpc.Server, srv ApplicationsServer) {
	s.RegisterService(&_Applications_serviceDesc, srv)
}

func _Applications_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/ListApplications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).ListApplications(ctx, req.(*ListApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_CreateApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Application)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).CreateApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/CreateApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).CreateApplication(ctx, req.(*Application))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_GetApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).GetApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/GetApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).GetApplication(ctx, req.(*GetApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Applications_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Application)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/soapbox.Applications/DeleteApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServer).DeleteApplication(ctx, req.(*Application))
	}
	return interceptor(ctx, in, info, handler)
}

var _Applications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "soapbox.Applications",
	HandlerType: (*ApplicationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApplications",
			Handler:    _Applications_ListApplications_Handler,
		},
		{
			MethodName: "CreateApplication",
			Handler:    _Applications_CreateApplication_Handler,
		},
		{
			MethodName: "GetApplication",
			Handler:    _Applications_GetApplication_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _Applications_DeleteApplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "application.proto",
}

func init() { proto1.RegisterFile("application.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdf, 0x6e, 0xda, 0x48,
	0x14, 0xc6, 0x31, 0x21, 0xb0, 0x39, 0xfc, 0xcd, 0xec, 0x6e, 0x32, 0x42, 0xab, 0xc4, 0x4b, 0xa5,
	0x06, 0xa1, 0x8a, 0xa8, 0xf4, 0xa6, 0x55, 0xd5, 0x0b, 0x82, 0x9d, 0x96, 0x2a, 0x0a, 0xd5, 0x60,
	0x1a, 0xa9, 0x37, 0x96, 0x83, 0x27, 0x64, 0x54, 0xe3, 0x99, 0x7a, 0x86, 0x28, 0x3c, 0x41, 0x1f,
	0xa7, 0xea, 0x1b, 0x56, 0xfe, 0x03, 0x18, 0xea, 0x48, 0xbd, 0x62, 0xe6, 0x3b, 0xdf, 0x19, 0x7d,
	0xfa, 0x9d, 0x83, 0xe1, 0xd0, 0x11, 0xc2, 0x63, 0x53, 0x47, 0x31, 0xee, 0x77, 0x45, 0xc0, 0x15,
	0x47, 0x25, 0xc9, 0x1d, 0x71, 0xcb, 0x1f, 0x9b, 0xd5, 0xe4, 0x10, 0xeb, 0xcd, 0xd3, 0x19, 0xe7,
	0x33, 0x8f, 0x9e, 0x47, 0xb7, 0xdb, 0xc5, 0xdd, 0xb9, 0x62, 0x73, 0x2a, 0x95, 0x33, 0x17, 0xb1,
	0xa1, 0xf5, 0xa3, 0x00, 0xe5, 0xfe, 0xe6, 0x39, 0x54, 0x83, 0x3c, 0x73, 0xb1, 0xa6, 0x6b, 0xed,
	0x7d, 0x92, 0x67, 0x2e, 0x3a, 0x86, 0xd2, 0x42, 0xd2, 0xc0, 0x66, 0x2e, 0xce, 0x47, 0x62, 0x31,
	0xbc, 0x0e, 0x5d, 0x84, 0xa0, 0xe0, 0x3b, 0x73, 0x8a, 0xf7, 0x74, 0xad, 0x7d, 0x40, 0xa2, 0x33,
	0xd2, 0xa1, 0xec, 0x52, 0x39, 0x0d, 0x98, 0x08, 0xdf, 0xc2, 0x85, 0xa8, 0x94, 0x96, 0xd0, 0xff,
	0x50, 0xa1, 0x8f, 0x8a, 0x06, 0xbe, 0xe3, 0xd9, 0xae, 0x2f, 0xf1, 0x7e, 0x6c, 0x59, 0x69, 0x86,
	0x2f, 0xd1, 0x73, 0xa8, 0xcf, 0x98, 0xba, 0x5f, 0xdc, 0xda, 0x01, 0x15, 0xdc, 0x5e, 0x04, 0x1e,
	0x2e, 0x46, 0xae, 0x6a, 0x2c, 0x13, 0x2a, 0xf8, 0x24, 0xf0, 0xd0, 0x19, 0xd4, 0x5d, 0x3e, 0xfd,
	0x4a, 0x83, 0x3b, 0xe6, 0x51, 0x5b, 0x38, 0xea, 0x1e, 0x97, 0x22, 0x5f, 0x6d, 0x23, 0x7f, 0x72,
	0xd4, 0x3d, 0x3a, 0x87, 0xbf, 0xa9, 0xaf, 0x82, 0xa5, 0xe0, 0xcc, 0x57, 0x36, 0x7f, 0xa0, 0x41,
	0xc0, 0x5c, 0x8a, 0xff, 0x8a, 0xcc, 0x68, 0x53, 0x1a, 0x25, 0x15, 0xf4, 0x02, 0x0a, 0x6a, 0x29,
	0x28, 0x3e, 0xd0, 0xb5, 0x76, 0xad, 0x87, 0xbb, 0x2b, 0xa4, 0x29, 0x4e, 0xd6, 0x52, 0x50, 0x12,
	0xb9, 0xd0, 0x1b, 0x80, 0x69, 0x40, 0x1d, 0x45, 0x5d, 0xdb, 0x51, 0x18, 0x74, 0xad, 0x5d, 0xee,
	0x35, 0xbb, 0x31, 0xf7, 0xee, 0x8a, 0x7b, 0xd7, 0x5a, 0x71, 0x27, 0x07, 0x89, 0xbb, 0xaf, 0x42,
	0x86, 0xd2, 0x5b, 0xcc, 0x70, 0x39, 0x66, 0x18, 0x9e, 0x43, 0x42, 0xcc, 0x4f, 0x11, 0xaa, 0xc4,
	0x84, 0x56, 0x5a, 0x48, 0xe8, 0x1d, 0xd4, 0xa2, 0x37, 0x18, 0xf7, 0x6d, 0xa9, 0x1c, 0x45, 0x71,
	0x35, 0x4a, 0x7a, 0xb4, 0x4e, 0x3a, 0x48, 0xca, 0xe3, 0xb0, 0x4a, 0xaa, 0xd3, 0xf4, 0x35, 0x6c,
	0x77, 0xa9, 0x47, 0x53, 0xed, 0xb5, 0x9d, 0x76, 0x23, 0x29, 0x27, 0xed, 0x6e, 0xfa, 0xda, 0x7a,
	0x09, 0x47, 0x57, 0x4c, 0xaa, 0x14, 0x0c, 0x42, 0xbf, 0x2d, 0xa8, 0x54, 0xe9, 0x5d, 0xd1, 0xd2,
	0xbb, 0xd2, 0x1a, 0xc3, 0xf1, 0x6f, 0x2d, 0x52, 0x70, 0x5f, 0x52, 0xf4, 0x1a, 0x2a, 0xa9, 0x6d,
	0x96, 0x58, 0xd3, 0xf7, 0xda, 0xe5, 0xde, 0x3f, 0x59, 0xcc, 0xc9, 0x96, 0xb3, 0x75, 0x06, 0xff,
	0xbe, 0xa7, 0x59, 0x31, 0x76, 0x56, 0xb8, 0xd3, 0x81, 0xfa, 0xce, 0xe4, 0x10, 0x40, 0x71, 0x6c,
	0x92, 0xcf, 0x26, 0x69, 0xe4, 0x50, 0x19, 0x4a, 0x03, 0x32, 0xba, 0xfe, 0x38, 0xba, 0x68, 0x68,
	0x9d, 0x07, 0xa8, 0x6e, 0xb1, 0x43, 0x27, 0xd0, 0x1c, 0x10, 0xb3, 0x6f, 0x99, 0xf6, 0xf0, 0xfa,
	0x92, 0xf4, 0xc7, 0x16, 0x99, 0x0c, 0xac, 0x09, 0x31, 0xed, 0x9b, 0xfe, 0xd0, 0x6a, 0xe4, 0xd0,
	0x33, 0x38, 0xcd, 0xae, 0x8f, 0x27, 0x83, 0x81, 0x69, 0x1a, 0xa6, 0xd1, 0xd0, 0x90, 0x0e, 0xff,
	0x65, 0x9b, 0x2e, 0xfb, 0xc3, 0x2b, 0xd3, 0x68, 0xe4, 0x3b, 0xdf, 0x35, 0xa8, 0x6e, 0x51, 0x47,
	0x75, 0x28, 0x5f, 0x8f, 0x2c, 0xdb, 0x30, 0xaf, 0x4c, 0xcb, 0x34, 0x1a, 0xb9, 0x30, 0x49, 0x7c,
	0xc9, 0x4c, 0xa2, 0x85, 0x49, 0xb2, 0xeb, 0x9b, 0x24, 0xf9, 0x30, 0x49, 0xb6, 0x29, 0x49, 0xb2,
	0xd7, 0xfb, 0x99, 0x87, 0x4a, 0x0a, 0x97, 0x44, 0x37, 0xd0, 0xd8, 0x19, 0x9e, 0x44, 0xa7, 0xeb,
	0xf9, 0x64, 0xaf, 0x42, 0x53, 0x7f, 0xda, 0x10, 0x0f, 0xbe, 0x95, 0x43, 0x7d, 0x38, 0x8c, 0x58,
	0xd3, 0xf4, 0xf7, 0x27, 0x73, 0xf2, 0xcd, 0x4c, 0xb5, 0x95, 0x43, 0x1f, 0xa0, 0xb6, 0xbd, 0x03,
	0xe8, 0x64, 0xed, 0xcc, 0x5c, 0x8e, 0x27, 0x5f, 0x7a, 0x0b, 0x87, 0x11, 0xff, 0x3f, 0x08, 0x53,
	0x5b, 0xab, 0xe6, 0x5c, 0xa8, 0x65, 0x2b, 0x77, 0x51, 0xfa, 0xb2, 0x1f, 0xff, 0xd1, 0x8b, 0xd1,
	0xcf, 0xab, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x88, 0x53, 0x76, 0x17, 0xa2, 0x05, 0x00, 0x00,
}
